// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stvcwpwfvlhcxwtzfgck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0dmN3cHdmdmxoY3h3dHpmZ2NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzOTcxMDMsImV4cCI6MjA2NDk3MzEwM30.bzvz6TVCq-dUIJgman9AfAcRZIGtSw7ikhxWuf7_Ceo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);